version: '2'
services:
  backend:
    build: backend
    ports:
      - "5000:5000"
    volumes:
      - ./Dropbox:/usr/src/app/remote
  frontend:
    build: frontend
    ports:
      - "80:80"
    volumes:
      - ./Dropbox:/usr/share/nginx/html/Dropbox
